version: "3"
services:
  rabitnode01:
    image: 499844677/rabbitmq:3.10.6-cluster
    container_name: rabbit-node01
    hostname: node01
    networks:
      - rabbit_cluster
    ports:
      - "15671:15672"
    volumes:
      - rabbit_node01_data:/var/lib/rabbitmq
      - rabbit_node01_config:/etc/rabbitmq
      - rabbit_node01_logs:/var/log/rabbitmq
    environment:
      - COOKIE_NAME=ACPWQONITDCYYBPNQRKP
  rabitnode02:
    image: 499844677/rabbitmq:3.10.6-cluster
    container_name: rabbit-node02
    hostname: node02
    networks:
      - rabbit_cluster
    ports:
      - "15672:15672"
    volumes:
      - rabbit_node02_data:/var/lib/rabbitmq
      - rabbit_node02_config:/etc/rabbitmq
      - rabbit_node02_logs:/var/log/rabbitmq
    environment:
      - COOKIE_NAME=ACPWQONITDCYYBPNQRKP
      - MASTER_NAME=rabbit@node01
    depends_on:
      - rabitnode01
  rabitnode03:
    image: 499844677/rabbitmq:3.10.6-cluster
    container_name: rabbit-node03
    hostname: node03
    networks:
      - rabbit_cluster
    ports:
      - "15673:15672"
    volumes:
      - rabbit_node03_data:/var/lib/rabbitmq
      - rabbit_node03_config:/etc/rabbitmq
      - rabbit_node03_logs:/var/log/rabbitmq
    environment:
      - COOKIE_NAME=ACPWQONITDCYYBPNQRKP
      - MASTER_NAME=rabbit@node01
    depends_on:
      - rabitnode01

  haproxy:
    image: 499844677/haproxy:2.6.2-rabbitmq
    container_name: rabbit-cluster-ha-proxy
    hostname: rabbit_cluster_ha
    networks:
      - rabbit_cluster
    ports:
      - "8100:8100"
      - "5672:5672"
    volumes:
      - rabbit_haproxy_cfg:/usr/local/etc/haproxy
    depends_on:
      - rabitnode01
      - rabitnode02
      - rabitnode03
volumes:
  rabbit_node01_data:
  rabbit_node01_logs:
  rabbit_node01_config:
  rabbit_node02_data:
  rabbit_node02_logs:
  rabbit_node02_config:
  rabbit_node03_data:
  rabbit_node03_logs:
  rabbit_node03_config:
  rabbit_haproxy_cfg:
networks:
  rabbit_cluster:
